---
- name: System packages
  tags: [packages]
  block:
    - name: Removal of packages from provisioner
      community.general.pacman:
        name:
          # misses clipboad feature, install gvim
          - vim
          # want v2 instead.
          - aws-cli
        state: removed
      become: yes
    - name: Install via pacman
      community.general.pacman:
        name:
          - bash-completion
          - bat
          - calibre
          - cmatrix
          - composer
          - ctags
          - dfu-programmer
          - dfu-util
          - diffpdf
          - fd
          - flameshot
          - gimagereader-gtk
          - github-cli
          - gvim
          - laptop-detect
          - lesspipe
          - lsd
          - meld
          - moreutils
          - mpv
          - ncdu
          - nethogs
          - nnn
          - p7zip
          - pacman-contrib
          - pkgfile
          - pv
          - qpdf
          - rlwrap
          - shellcheck
          - sshfs
          - strace
          - sxiv
          - teensy-loader-cli
          - telegram-desktop
          - tesseract
          - tesseract-data-eng
          - tesseract-data-ita
          - tesseract-data-spa
          - the_silver_searcher
          - tig
          - tlp
          - units
          - unrar
          - virtualbox
          - virtualbox
          - virtualbox-guest-iso
          - virtualbox-guest-utils
          - virtualbox-host-dkms
          - xclip
          - xdg-utils
          - xsel
      become: yes
    - name: Install via paru (aur)
      kewlfft.aur.aur:
        use: paru
        name:
          - navi
          - cheat
          - neovim-nightly-bin
          - dropbox
          - aws-cli-v2-bin
          - chrome-gnome-shell
          - python-neovim-git
          - nerd-fonts-source-code-pro
          - nordvpn-bin
          - autokey-gtk
      become: yes
      become_user: aur_builder
