---
- name: Arch Packages
  import_tasks: arch_packages.yml
  #when: ansible_facts['os_family'] == "ArchLinux"
- name: NPM Packages
  import_tasks: npm_packages.yml
- name: Permissions (sudoers)
  import_tasks: sudoers.yml
- name: Locales
  import_tasks: locales.yml
